server:
  port: 8080
  
spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    fetch-registry: true
    register-with-eureka: false
  instance:
    hostname: localhost

ribbon:
  eager-load:
    enabled: true
